version: "3.8"
services:
  api:
    image: thumbnail-api
    build: .
    ports:
      - "3000:3000"
    environment: 
      SERVER_TYPE: server
      SERVER_PORT: 3000
    env_file: local.env
    depends_on: 
      - db
      - s3
  task:
    image: thumbnail-task
    build: .
    environment: 
      SERVER_TYPE: worker
    env_file: local.env
    depends_on: 
      - db
      - s3
  metrics:
    image: thumbnail-task
    build: .
    environment: 
      SERVER_TYPE: metrics
      METRICS_PORT: 9190
    env_file: local.env
    depends_on: 
      - db
      - s3
      - task
    ports:
      - "9190:9190"
  db:
    image : mongo
    volumes:
      - ./data/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./data/minio:/data
    env_file: local.env
    command: server /data