apiVersion: batch/v1
kind: Job
metadata:
  name: minio-restore
spec:
  template:
    spec:
      containers:
      - name: minio-backup
        image: harsh7896/backup:miniopsv1
        imagePullPolicy: "Always"
        env:
          - name: REGION
            value: ap-south-1
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /root/credentials
          - name: AWS_CONFIG_FILE
            value: /root/config
          - name: OPS
            value: "RESTORE"
          - name: BUCKET
            value: "miniodumpshvvit7896"
          - name: MINIO_ACCESS_KEY_ID
            value: someaccesskey
          - name: MINIO_SECRET_ACCESS_KEY
            value: somesecretkey
        command: ['bash', "-c","./ops.sh"]
        volumeMounts:
         - name: aws-cred
           mountPath: "/root/credentials"
           subPath: credentials
         - name: aws-cred
           mountPath: "/root/config"
           subPath: config
      restartPolicy: OnFailure
      volumes:
        - name: aws-cred
          secret:
            secretName: aws
  backoffLimit: 4