apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-app
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: deployments/dev/minio
    repoURL: https://github.com/hvvit/devops-assignment-thumbnail-generator-api
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true