apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-app
  namespace: argocd
spec:
  destination:
    namespace: mongo
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: deployments/dev/mongoDB
    repoURL: https://github.com/hvvit/testcicd
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true