apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thumbnail-generator-app
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: task
    namespace: thumbnail-generator
    jsonPointers:
    - /spec/replicas
  destination:
    namespace: thumbnail-generator
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: deployments/dev/thumbnail-generator
    repoURL: https://github.com/hvvit/devops-assignment-thumbnail-generator-api
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true