apiVersion: v1
data:
  MINIO_ACCESS_KEY: someaccesskey
  MINIO_ENDPOINT: s3.minio.svc.cluster.local
  MINIO_PORT: "9000"
  MINIO_SECRET_KEY: somesecretkey
  MINIO_USE_SSL: "false"
  MONGO_URL: mongodb://db.mongo.svc.cluster.local:27017
kind: ConfigMap
metadata:
  namespace: thumbnail-generator
  labels:
    service: api-local-env
  name: local-env