apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: thumbnailgentask
  namespace: thumbnail-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: num_of_requests_in_waiting
      targetAverageValue: "30"