apiVersion: v1
kind: Service
metadata:
  labels:
    service: metrics
  name: metrics
  namespace: thumbnail-generator
spec:
  ports:
    - name: "metrics"
      port: 9190
      targetPort: 9190
  selector:
    service: task
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: api
  namespace: thumbnail-generator
spec:
  ports:
    - name: "api"
      port: 3000
      targetPort: 3000
  selector:
    service: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: apinodeport
  namespace: thumbnail-generator
spec:
  type: NodePort
  ports:
    - name: "api"
      port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    service: api