apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: db
  name: db
  namespace: mongo
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
      annotations:
        backup.velero.io/backup-volumes: db-claim0
    spec:
      containers:
        - image: mongo
          name: db
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: db-claim0
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
