apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: db-claim0
  name: db-claim0
  namespace: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5100Mi