apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: mongo
spec:
  ports:
    - name: "mongo"
      port: 27017
      targetPort: 27017
  selector:
    service: db
