name: Build Project
on:
  push:
    paths-ignore:
      - 'build/**'
      - 'deployments/**'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

permissions:
  contents: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '14.18.0'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Tests
      run: npm run test

    - name: Run Build
      run: npm run build

    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: build docker image
      run: docker build -t harsh7896/assignment:project.${GITHUB_SHA::6} .

    - name: push docker image
      run: docker push harsh7896/assignment:project.${GITHUB_SHA::6}

    - name: image name
      run: echo "harsh7896/assignment:project.${GITHUB_SHA::6}"

    - name: change image for deployment
      run: |
        sed -i "s#image:.*#image: harsh7896/assignment:project.${GITHUB_SHA::6}#g" deployments/dev/thumbnail-generator/deployments.yaml

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automation for deployment changes
        file_pattern: deployments/dev/thumbnail-generator/deployments.yaml
        commit_author: Author <actions@github.com>