name: Build Project
on:
  push:
    paths-ignore:
      - 'build/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '14.18.0'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Tests
      run: npm run test

    - name: Run Build
      run: npm run build

    - name: build docker image and push
      run: docker build -t harsh7896/assignment:project.${GITHUB_SHA::6}
  
    